// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGau6DxJDqWnGyvfvgim6j_VgiO6gKbno',
    appId: '1:782692490355:web:2bb1bf655ffb774befde06',
    messagingSenderId: '782692490355',
    projectId: 'ponenciapp',
    authDomain: 'ponenciapp.firebaseapp.com',
    storageBucket: 'ponenciapp.firebasestorage.app',
    measurementId: 'G-6C4ZEB2QSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTi6esLaEHtyNvs6Ex7vxWfMYeP5Og9XQ',
    appId: '1:782692490355:android:336d59140e5a0226efde06',
    messagingSenderId: '782692490355',
    projectId: 'ponenciapp',
    storageBucket: 'ponenciapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMkJlnGV_JQP2Pepba0fAMokEWlPpZ_wQ',
    appId: '1:782692490355:ios:f569529fc37e038befde06',
    messagingSenderId: '782692490355',
    projectId: 'ponenciapp',
    storageBucket: 'ponenciapp.firebasestorage.app',
    iosBundleId: 'com.example.ponenciapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMkJlnGV_JQP2Pepba0fAMokEWlPpZ_wQ',
    appId: '1:782692490355:ios:f569529fc37e038befde06',
    messagingSenderId: '782692490355',
    projectId: 'ponenciapp',
    storageBucket: 'ponenciapp.firebasestorage.app',
    iosBundleId: 'com.example.ponenciapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGau6DxJDqWnGyvfvgim6j_VgiO6gKbno',
    appId: '1:782692490355:web:b469eaeec80e7ca8efde06',
    messagingSenderId: '782692490355',
    projectId: 'ponenciapp',
    authDomain: 'ponenciapp.firebaseapp.com',
    storageBucket: 'ponenciapp.firebasestorage.app',
    measurementId: 'G-WSJ1P9RLX6',
  );
}
